services:
  api:
    image: natts00nb/bookify:latest
    container_name: bookify-api
    env_file:
      - .env
    environment:
      NODE_ENV: deployment
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - postgres
    restart: always

  postgres:
    image: postgres:15.3
    container_name: nestjs-postgres
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: nestjs-pgadmin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres
    env_file:
      - docker.env

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
